### ISSUE TITLE
Erreur 

### ISSUE THREAD

**Issue by vptcnt** [hacf-fr/hass-ecoledirecte#3]
Bonsoir,

L'installation se passe bien : login et mot de passe sont entrés correctement - mais je ne vois pas les "sensors" pour les enfants.
Par contre, dans le journal, j'ai un message d'erreur :

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ecole_directe/sensor.py", line 48, in async_setup_entry
    sensors.append(EDHomeworksSensor(coordinator, eleve))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecole_directe/sensor.py", line 160, in __init__
    f"homeworks{self._child_info.get_fullname_lower()}",
                ^^^^^^^^^^^^^^^^
AttributeError: 'EDHomeworksSensor' object has no attribute '_child_info'

J'utilise la dernière version de HA OS et dernière version du Core

**Comment by vptcnt** [comment]
Merci.
Cela fonctionne mieux ;-) Mes 3 enfants remontent bien dans les sensors.

À quoi correspondent les valeurs de 
ecole_directe_XXXX_YYYYY_homeworks (j'ai une valeur numérique)
et 
ecole_directe_XXXX_YYYYY_grades (j'ai une alterne de 0 et de 5 chaque 30 min )



Par contre, j'ai une nouvelle erreur dans le journal :

Enregistreur: custom_components.ecole_directe.coordinator
Source: custom_components/ecole_directe/coordinator.py:130
intégration: Ecole Directe (documentation, problèmes)
S'est produit pour la première fois: 12:34:57 (30 occurrences)
Dernier enregistrement: 21:57:23

Error getting grades from ecole directe: 'date'

**Comment by Giga77** [comment]
Je t'invite à regarder cette discussion : https://forum.hacf.fr/t/integration-ecole-directe-version-alpha-0-0-10/38119

ecole_directe_XXXX_YYYYY_homeworks ça correspond aux devoirs, tu peux les voir dans les attributs du capteurs

ecole_directe_XXXX_YYYYY_grades ce sont les dernières notes,  tu peux aussi les voir dans les attributs du capteurs
Mais à priori, il doit y avoir une erreur

**Comment by vptcnt** [comment]
Je suis allé voir le forum que vous m'avez indiqué et j'ai compris comment fonctionne les valeurs retournées. Pas trop l'habitude de valeurs sous forme de Json.
Merci encore..
J'ai pu affiché donc les notes pour le moment.
Par contre uniquement pour 30 min.
Et puis rien pendant 30min , et ainsi de suite .

Que puis je vous envoyer pour aider à comprendre ce qui se passe

**Comment by Giga77** [comment]
J'ai apporté une correction au code, en espérant que ça régle le soucis.
