### ISSUE TITLE
dernière version compatible avec tous les établissements ?

### ISSUE THREAD

**Issue by J-Dudek** [hacf-fr/hass-ecoledirecte#44]
Bonjour,

aussitôt la version [0.3.15](https://github.com/hacf-fr/hass-ecoledirecte/releases/tag/v0.3.15) sortie je me suis dit "génial une nouvelle feature" mais visiblement l'intégration fonctionne avec mon fils qui est au lycée mais pas ma fille qui est en collège dans un autre établissement.

J'ai supprimé son compte et refait l'ajout mais pas moyen.

Dans le doute j'ai supprimé l'intégration et l'application, réinstaller la dernière version et le problème persiste.

au regard des logs
```
2024-10-17 23:40:33.653 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ecole_directe platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/ecole_directe/sensor.py", line 67, in async_setup_entry
disciplines = coordinator.data[f"{eleve.get_fullname_lower()}_disciplines"]
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'c******_******_disciplines'
2024-10-17 23:41:04.729 WARNING (SyncWorker_12) [custom_components.ecole_directe.ecole_directe_helper] get_periode: 'appreciations'
2024-10-17 23:41:04.733 WARNING (MainThread) [custom_components.ecole_directe.coordinator] Error getting grades from ecole directe: 'appreciations'
2024-10-17 23:41:06.132 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ecole_directe platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/ecole_directe/sensor.py", line 67, in async_setup_entry
disciplines = coordinator.data[f"{eleve.get_fullname_lower()}_disciplines"]
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '*******_********_disciplines'
```

Pour le coup, je n'explique pas. Les json en réponse semblent très ressemblant.

![image](https://github.com/user-attachments/assets/8a4a209b-1b11-4f27-b401-88a25b234086)

le service ne s'initialise donc pas et les entités ne remontent pas.

Une idée ?

**Comment by J-Dudek** [comment]
je complète,
visiblement [cette partie](https://github.com/hacf-fr/hass-ecoledirecte/blob/68290674a239cc75c7a08a1348cb0319a589a24a/custom_components/ecole_directe/ecole_directe_helper.py#L584) pose problème dans mon cas car il n'y a pas le `"appreciations": []` dans le json retournée par le collège.

**Comment by Giga77** [comment]
Merci pour le fix
