### ISSUE TITLE
plus d'entités

### ISSUE THREAD

**Issue by mattnemoz** [hacf-fr/hass-ecoledirecte#47]
Bonjour,
J'ai mis à jour l'application, qui fonctionnait très bien.
Depuis, je n'ai plus rien...
J'ai tenté de désinstaller complètement et de réinstaller le plugin, j'ai bien la dernière version à cette date :
![image](https://github.com/user-attachments/assets/8b6ea114-884b-4b22-a6fe-af884b643395)
Quand j'ajoute l'intégration, je renseigne mon login et mot de passe, et cela rajoute bien une entrée dans l'intégration, mais aucun appareil ni entité :
![image](https://github.com/user-attachments/assets/99fd2258-ef96-41ad-997c-1db74685073e)
On voit d'ailleurs un bug sur l'intégration qui indique qu'on est en version 0.3.11 alors que j'ai bien redémarré entre la désinstallation et la réinstallation, et suite à la réinstallation également.
Quelqu'un pour m'aider SVP ?

**Comment by Giga77** [comment]
Hello
Il me faudrait les logs.

**Comment by mattnemoz** [comment]
Bonjour,
Dans les logs, voici ce que j'ai :
![image](https://github.com/user-attachments/assets/785bd429-3b69-4f15-b74c-5eb87b97ef01)
![image](https://github.com/user-attachments/assets/9f40b24b-dc97-4650-b14e-30a18d4e3186)

Dans Studio Code, je vois bien les fichiers d'imports réalisés :
![image](https://github.com/user-attachments/assets/ea420035-01db-45ab-980c-6a236f5515ea)

Cela semble venir de la ligne 67 de sensor.py : 
![image](https://github.com/user-attachments/assets/7e3c3f8a-c7f4-4295-86a5-4c25bc95be1f)

Dans l'extraction des logs, je n'ai rien d'autre que cela au sujet d'ecole direct : 
2024-10-24 11:57:25.938 WARNING (MainThread) [custom_components.ecole_directe.coordinator] Error getting grades from ecole directe: 'moyenneGenerale'
2024-10-24 11:57:26.819 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ecole_directe platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ecole_directe/sensor.py", line 67, in async_setup_entry
    disciplines = coordinator.data[f"{eleve.get_fullname_lower()}_disciplines"]
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'lucas_nemoz_disciplines'

**Comment by J-Dudek** [comment]
Au niveau des retours de l'appel api via le site école directe tu as quoi dans ton json ?
À première vue il semble y avoir un nulle quelque part.

**Comment by mattnemoz** [comment]
Dans quels fichiers ?
les json ne sont pas vides, et mes 2 enfants apparaissent bien dedans :
![image](https://github.com/user-attachments/assets/b770123a-f62b-4338-aca4-77d4630b7a70)

**Comment by mattnemoz** [comment]
La comparaison : 
--- {
+++ {
@@ -74,16 +74,7 @@
                   "nomPP": {
                     "type": "string"
                   },
-                  "appreciationPP": {
-                    "type": "string"
-                  },
                   "nomCE": {
-                    "type": "string"
-                  },
-                  "appreciationCE": {
-                    "type": "string"
-                  },
-                  "appreciationVS": {
                     "type": "string"
                   },
                   "decisionDuConseil": {
@@ -159,10 +150,6 @@
                               "nom"
                             ]
                           }
-                        },
-                        "appreciations": {
-                          "type": "array",
-                          "items": {}
                         }
                       },
                       "required": [
@@ -178,8 +165,7 @@
                         "option",
                         "sousMatiere",
                         "saisieAppreciationSSMat",
-                        "professeurs",
-                        "appreciations"
+                        "professeurs"
                       ]
                     }
                   },
@@ -191,10 +177,7 @@
                 "required": [
                   "dateCalcul",
                   "nomPP",
-                  "appreciationPP",
                   "nomCE",
-                  "appreciationCE",
-                  "appreciationVS",
                   "decisionDuConseil",
                   "disciplines",
                   "disciplinesSimulation"
@@ -277,15 +260,47 @@
               "moyenneClasse": {
                 "type": "string"
               },
-              "minClasse": {
-                "type": "string"
-              },
-              "maxClasse": {
-                "type": "string"
-              },
               "elementsProgramme": {
                 "type": "array",
-                "items": {}
+                "items": {
+                  "type": "object",
+                  "properties": {
+                    "descriptif": {
+                      "type": "string"
+                    },
+                    "idElemProg": {
+                      "type": "number"
+                    },
+                    "valeur": {
+                      "type": "string"
+                    },
+                    "cdt": {
+                      "type": "boolean"
+                    },
+                    "idCompetence": {
+                      "type": "number"
+                    },
+                    "idConnaissance": {
+                      "type": "number"
+                    },
+                    "libelleCompetence": {
+                      "type": "string"
+                    },
+                    "afc": {
+                      "type": "number"
+                    }
+                  },
+                  "required": [
+                    "descriptif",
+                    "idElemProg",
+                    "valeur",
+                    "cdt",
+                    "idCompetence",
+                    "idConnaissance",
+                    "libelleCompetence",
+                    "afc"
+                  ]
+                }
               }
             },
             "required": [
@@ -308,8 +323,6 @@
               "valeurisee",
               "nonSignificatif",
               "moyenneClasse",
-              "minClasse",
-              "maxClasse",
               "elementsProgramme"
             ]
           }
@@ -582,13 +595,103 @@
             "libellesAppreciations",
             "appreciationsParametrage"
           ]
+        },
+        "LSUN": {
+          "type": "object",
+          "properties": {
+            "A001": {
+              "type": "array",
+              "items": {
+                "type": "object",
+                "properties": {
+                  "cdt": {
+                    "type": "boolean"
+                  },
+                  "codeMatiere": {
+                    "type": "string"
+                  },
+                  "libelleMatiere": {
+                    "type": "string"
+                  },
+                  "isFirstOfMatiere": {
+                    "type": "boolean"
+                  },
+                  "nbElemProgMatiere": {
+                    "type": "number"
+                  },
+                  "codeSousMatiere": {
+                    "type": "string"
+                  },
+                  "libelleSousMatiere": {
+                    "type": "string"
+                  },
+                  "isFirstOfSousMatiere": {
+                    "type": "boolean"
+                  },
+                  "nbElemProgSousMatiere": {
+                    "type": "number"
+                  },
+                  "libelleElementProgramme": {
+                    "type": "string"
+                  },
+                  "idElemProg": {
+                    "type": "number"
+                  },
+                  "valeur": {
+                    "type": "string"
+                  },
+                  "afc": {
+                    "type": "number"
+                  },
+                  "professeurs": {
+                    "type": "array",
+                    "items": {
+                      "type": "object",
+                      "properties": {
+                        "id": {
+                          "type": "number"
+                        },
+                        "nom": {
+                          "type": "string"
+                        }
+                      },
+                      "required": [
+                        "id",
+                        "nom"
+                      ]
+                    }
+                  }
+                },
+                "required": [
+                  "cdt",
+                  "codeMatiere",
+                  "libelleMatiere",
+                  "isFirstOfMatiere",
+                  "nbElemProgMatiere",
+                  "codeSousMatiere",
+                  "libelleSousMatiere",
+                  "isFirstOfSousMatiere",
+                  "nbElemProgSousMatiere",
+                  "libelleElementProgramme",
+                  "idElemProg",
+                  "valeur",
+                  "afc",
+                  "professeurs"
+                ]
+              }
+            }
+          },
+          "required": [
+            "A001"
+          ]
         }
       },
       "required": [
         "foStat",
         "periodes",
         "notes",
-        "parametrage"
+        "parametrage",
+        "LSUN"
       ]
     }
   },

**Comment by J-Dudek** [comment]
@mattnemoz  tu peux essayer la méthode que je t'ai donné au dessus?  car la c'est très peu lisible ...

**Comment by mattnemoz** [comment]
Voici le schéma json : 

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "code": {
      "type": "number"
    },
    "token": {
      "type": "string"
    },
    "host": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {
        "foStat": {
          "type": "string"
        },
        "periodes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "idPeriode": {
                "type": "string"
              },
              "codePeriode": {
                "type": "string"
              },
              "periode": {
                "type": "string"
              },
              "annuel": {
                "type": "boolean"
              },
              "dateDebut": {
                "type": "string"
              },
              "dateFin": {
                "type": "string"
              },
              "examenBlanc": {
                "type": "boolean"
              },
              "cloture": {
                "type": "boolean"
              },
              "dateConseil": {
                "type": "string"
              },
              "moyNbreJoursApresConseil": {
                "type": "number"
              },
              "ensembleMatieres": {
                "type": "object",
                "properties": {
                  "dateCalcul": {
                    "type": "string"
                  },
                  "moyenneGenerale": {
                    "type": "string"
                  },
                  "moyenneClasse": {
                    "type": "string"
                  },
                  "moyenneMin": {
                    "type": "string"
                  },
                  "moyenneMax": {
                    "type": "string"
                  },
                  "nomPP": {
                    "type": "string"
                  },
                  "nomCE": {
                    "type": "string"
                  },
                  "decisionDuConseil": {
                    "type": "string"
                  },
                  "disciplines": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "codeMatiere": {
                          "type": "string"
                        },
                        "codeSousMatiere": {
                          "type": "string"
                        },
                        "discipline": {
                          "type": "string"
                        },
                        "moyenne": {
                          "type": "string"
                        },
                        "moyenneClasse": {
                          "type": "string"
                        },
                        "moyenneMin": {
                          "type": "string"
                        },
                        "moyenneMax": {
                          "type": "string"
                        },
                        "coef": {
                          "type": "number"
                        },
                        "effectif": {
                          "type": "number"
                        },
                        "rang": {
                          "type": "number"
                        },
                        "groupeMatiere": {
                          "type": "boolean"
                        },
                        "idGroupeMatiere": {
                          "type": "number"
                        },
                        "option": {
                          "type": "number"
                        },
                        "sousMatiere": {
                          "type": "boolean"
                        },
                        "saisieAppreciationSSMat": {
                          "type": "boolean"
                        },
                        "professeurs": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "nom": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "id",
                              "nom"
                            ]
                          }
                        }
                      },
                      "required": [
                        "id",
                        "codeMatiere",
                        "codeSousMatiere",
                        "discipline",
                        "coef",
                        "effectif",
                        "rang",
                        "groupeMatiere",
                        "idGroupeMatiere",
                        "option",
                        "sousMatiere",
                        "saisieAppreciationSSMat",
                        "professeurs"
                      ]
                    }
                  },
                  "disciplinesSimulation": {
                    "type": "array",
                    "items": {}
                  }
                },
                "required": [
                  "dateCalcul",
                  "nomPP",
                  "nomCE",
                  "decisionDuConseil",
                  "disciplines",
                  "disciplinesSimulation"
                ]
              }
            },
            "required": [
              "idPeriode",
              "codePeriode",
              "periode",
              "annuel",
              "dateDebut",
              "dateFin",
              "examenBlanc",
              "cloture",
              "moyNbreJoursApresConseil",
              "ensembleMatieres"
            ]
          }
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "devoir": {
                "type": "string"
              },
              "codePeriode": {
                "type": "string"
              },
              "codeMatiere": {
                "type": "string"
              },
              "libelleMatiere": {
                "type": "string"
              },
              "codeSousMatiere": {
                "type": "string"
              },
              "typeDevoir": {
                "type": "string"
              },
              "enLettre": {
                "type": "boolean"
              },
              "commentaire": {
                "type": "string"
              },
              "uncSujet": {
                "type": "string"
              },
              "uncCorrige": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "dateSaisie": {
                "type": "string"
              },
              "coef": {
                "type": "string"
              },
              "noteSur": {
                "type": "string"
              },
              "valeur": {
                "type": "string"
              },
              "valeurisee": {
                "type": "boolean"
              },
              "nonSignificatif": {
                "type": "boolean"
              },
              "moyenneClasse": {
                "type": "string"
              },
              "elementsProgramme": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "descriptif": {
                      "type": "string"
                    },
                    "idElemProg": {
                      "type": "number"
                    },
                    "valeur": {
                      "type": "string"
                    },
                    "cdt": {
                      "type": "boolean"
                    },
                    "idCompetence": {
                      "type": "number"
                    },
                    "idConnaissance": {
                      "type": "number"
                    },
                    "libelleCompetence": {
                      "type": "string"
                    },
                    "afc": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "descriptif",
                    "idElemProg",
                    "valeur",
                    "cdt",
                    "idCompetence",
                    "idConnaissance",
                    "libelleCompetence",
                    "afc"
                  ]
                }
              }
            },
            "required": [
              "id",
              "devoir",
              "codePeriode",
              "codeMatiere",
              "libelleMatiere",
              "codeSousMatiere",
              "typeDevoir",
              "enLettre",
              "commentaire",
              "uncSujet",
              "uncCorrige",
              "date",
              "dateSaisie",
              "coef",
              "noteSur",
              "valeur",
              "valeurisee",
              "nonSignificatif",
              "moyenneClasse",
              "elementsProgramme"
            ]
          }
        },
        "parametrage": {
          "type": "object",
          "properties": {
            "couleurEval1": {
              "type": "string"
            },
            "couleurEval2": {
              "type": "string"
            },
            "couleurEval3": {
              "type": "string"
            },
            "couleurEval4": {
              "type": "string"
            },
            "libelleEval1": {
              "type": "string"
            },
            "libelleEval2": {
              "type": "string"
            },
            "libelleEval3": {
              "type": "string"
            },
            "libelleEval4": {
              "type": "string"
            },
            "affichageMoyenne": {
              "type": "boolean"
            },
            "affichageMoyenneDevoir": {
              "type": "boolean"
            },
            "affichagePositionMatiere": {
              "type": "boolean"
            },
            "affichageOngletCompetence": {
              "type": "number"
            },
            "affichageNote": {
              "type": "boolean"
            },
            "affichageCompetence": {
              "type": "boolean"
            },
            "affichageEvaluationsComposantes": {
              "type": "boolean"
            },
            "affichageGraphiquesComposantes": {
              "type": "boolean"
            },
            "modeCalculGraphiquesComposantes": {
              "type": "string"
            },
            "affichageCompNum": {
              "type": "boolean"
            },
            "libelleEvalCompNum1": {
              "type": "string"
            },
            "libelleEvalCompNum2": {
              "type": "string"
            },
            "libelleEvalCompNum3": {
              "type": "string"
            },
            "affichageAppreciation": {
              "type": "boolean"
            },
            "appreciationsProf": {
              "type": "boolean"
            },
            "appreciationProfPrinc": {
              "type": "boolean"
            },
            "affichageMention": {
              "type": "boolean"
            },
            "affichageAppreciationCE": {
              "type": "boolean"
            },
            "affichageAppreciationVS": {
              "type": "boolean"
            },
            "affichageAppreciationCN": {
              "type": "boolean"
            },
            "affichageAppreciationClasse": {
              "type": "boolean"
            },
            "affichageAppreciationPeriodeCloturee": {
              "type": "boolean"
            },
            "moyenneUniquementPeriodeCloture": {
              "type": "boolean"
            },
            "moyennePeriodeReleve": {
              "type": "boolean"
            },
            "moyennePeriodeAnnuelle": {
              "type": "boolean"
            },
            "moyennePeriodeHorsP": {
              "type": "boolean"
            },
            "moyenneEleveDansNotes": {
              "type": "boolean"
            },
            "moyenneEleve": {
              "type": "boolean"
            },
            "moyenneEleveDansMoyenne": {
              "type": "boolean"
            },
            "moyenneGenerale": {
              "type": "boolean"
            },
            "moyenneCoefMatiere": {
              "type": "boolean"
            },
            "moyenneClasse": {
              "type": "boolean"
            },
            "moyenneMin": {
              "type": "boolean"
            },
            "moyenneMax": {
              "type": "boolean"
            },
            "moyenneRang": {
              "type": "boolean"
            },
            "moyenneSur": {
              "type": "number"
            },
            "moyenneGraphique": {
              "type": "boolean"
            },
            "moyennesSimulation": {
              "type": "boolean"
            },
            "coefficientNote": {
              "type": "boolean"
            },
            "colonneCoefficientMatiere": {
              "type": "boolean"
            },
            "noteGrasSousMoyenne": {
              "type": "boolean"
            },
            "noteGrasAudessusMoyenne": {
              "type": "boolean"
            },
            "libelleDevoir": {
              "type": "boolean"
            },
            "dateDevoir": {
              "type": "boolean"
            },
            "typeDevoir": {
              "type": "boolean"
            },
            "noteUniquementPeriodeCloture": {
              "type": "boolean"
            },
            "notePeriodeReleve": {
              "type": "boolean"
            },
            "notePeriodeAnnuelle": {
              "type": "boolean"
            },
            "notePeriodeHorsP": {
              "type": "boolean"
            },
            "libellesAppreciations": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "appreciationsParametrage": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "code": {
                    "type": "string"
                  },
                  "id": {
                    "type": "number"
                  },
                  "nbMaxCaractere": {
                    "type": "number"
                  },
                  "libelle": {
                    "type": "string"
                  }
                },
                "required": [
                  "code",
                  "id",
                  "nbMaxCaractere",
                  "libelle"
                ]
              }
            }
          },
          "required": [
            "couleurEval1",
            "couleurEval2",
            "couleurEval3",
            "couleurEval4",
            "libelleEval1",
            "libelleEval2",
            "libelleEval3",
            "libelleEval4",
            "affichageMoyenne",
            "affichageMoyenneDevoir",
            "affichagePositionMatiere",
            "affichageOngletCompetence",
            "affichageNote",
            "affichageCompetence",
            "affichageEvaluationsComposantes",
            "affichageGraphiquesComposantes",
            "modeCalculGraphiquesComposantes",
            "affichageCompNum",
            "libelleEvalCompNum1",
            "libelleEvalCompNum2",
            "libelleEvalCompNum3",
            "affichageAppreciation",
            "appreciationsProf",
            "appreciationProfPrinc",
            "affichageMention",
            "affichageAppreciationCE",
            "affichageAppreciationVS",
            "affichageAppreciationCN",
            "affichageAppreciationClasse",
            "affichageAppreciationPeriodeCloturee",
            "moyenneUniquementPeriodeCloture",
            "moyennePeriodeReleve",
            "moyennePeriodeAnnuelle",
            "moyennePeriodeHorsP",
            "moyenneEleveDansNotes",
            "moyenneEleve",
            "moyenneEleveDansMoyenne",
            "moyenneGenerale",
            "moyenneCoefMatiere",
            "moyenneClasse",
            "moyenneMin",
            "moyenneMax",
            "moyenneRang",
            "moyenneSur",
            "moyenneGraphique",
            "moyennesSimulation",
            "coefficientNote",
            "colonneCoefficientMatiere",
            "noteGrasSousMoyenne",
            "noteGrasAudessusMoyenne",
            "libelleDevoir",
            "dateDevoir",
            "typeDevoir",
            "noteUniquementPeriodeCloture",
            "notePeriodeReleve",
            "notePeriodeAnnuelle",
            "notePeriodeHorsP",
            "libellesAppreciations",
            "appreciationsParametrage"
          ]
        },
        "LSUN": {
          "type": "object",
          "properties": {
            "A001": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "cdt": {
                    "type": "boolean"
                  },
                  "codeMatiere": {
                    "type": "string"
                  },
                  "libelleMatiere": {
                    "type": "string"
                  },
                  "isFirstOfMatiere": {
                    "type": "boolean"
                  },
                  "nbElemProgMatiere": {
                    "type": "number"
                  },
                  "codeSousMatiere": {
                    "type": "string"
                  },
                  "libelleSousMatiere": {
                    "type": "string"
                  },
                  "isFirstOfSousMatiere": {
                    "type": "boolean"
                  },
                  "nbElemProgSousMatiere": {
                    "type": "number"
                  },
                  "libelleElementProgramme": {
                    "type": "string"
                  },
                  "idElemProg": {
                    "type": "number"
                  },
                  "valeur": {
                    "type": "string"
                  },
                  "afc": {
                    "type": "number"
                  },
                  "professeurs": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "nom": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "nom"
                      ]
                    }
                  }
                },
                "required": [
                  "cdt",
                  "codeMatiere",
                  "libelleMatiere",
                  "isFirstOfMatiere",
                  "nbElemProgMatiere",
                  "codeSousMatiere",
                  "libelleSousMatiere",
                  "isFirstOfSousMatiere",
                  "nbElemProgSousMatiere",
                  "libelleElementProgramme",
                  "idElemProg",
                  "valeur",
                  "afc",
                  "professeurs"
                ]
              }
            }
          },
          "required": [
            "A001"
          ]
        }
      },
      "required": [
        "foStat",
        "periodes",
        "notes",
        "parametrage",
        "LSUN"
      ]
    }
  },
  "required": [
    "code",
    "token",
    "host",
    "data"
  ]
}
```

**Comment by mattnemoz** [comment]
Pour tester je viens de faire un retour arriere en V0.10, je récupère bien le service et les entités : 

![image](https://github.com/user-attachments/assets/28453df3-a4fc-410a-88b1-f97e095237bd)

![image](https://github.com/user-attachments/assets/5c730d20-2e78-4332-9c4a-046902cf905f)

**Comment by J-Dudek** [comment]
Oui, elle sont indisponibles car l'initialisation raise avant la fin.

c'est possible que le code en question soit à ce niveau[ la](https://github.com/hacf-fr/hass-ecoledirecte/blob/7927520c4bb7720006afbdf5e44f84896d0b43d7/custom_components/ecole_directe/ecole_directe_helper.py#L570)..mais je n'ai pas de certitude.

peux-tu fournir le json (celui ou tu as extrait le schéma précédemment)  complet repris d'ecoledirecte en l'anonymisant niveau nom / prénom et id technique  ?

**Comment by mattnemoz** [comment]
Je mets les json des notes pour les 2 enfants, enfant1 au collège et enfant2 en primaire.

[enfant1.json](https://github.com/user-attachments/files/17509281/enfant1.json)
[enfant2.json](https://github.com/user-attachments/files/17509282/enfant2.json)

**Comment by J-Dudek** [comment]
C'est en effet un soucis de champs. 
C'est assez étrange le fait que appréciations ne soit pas toujours présent.

@Giga77 ils n'ont pas de standard ou on pourrait avoir les champs obligatoires et facultatifdms au retour ?

**Comment by mattnemoz** [comment]
Ok super, merci @J-Dudek !
Je passe en résolu, et j'attends le pull pour la mise à jour !

**Comment by Giga77** [comment]
@mattnemoz Il y a une PR lié à ton issue.
La fermeture de la PR va automatiquement fermé l'issue .
